//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avista.ESB.Testing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avista.ESB.Testing.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;s:Body&gt;{0}&lt;/s:Body&gt;&lt;/s:Envelope&gt;.
        /// </summary>
        internal static string soap11Envelope {
            get {
                return ResourceManager.GetString("soap11Envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap:Body&gt;&lt;soap:Fault&gt;&lt;faultcode&gt;{0}&lt;/faultcode&gt;&lt;faultstring&gt;{1}&lt;/faultstring&gt;&lt;detail&gt;{2}&lt;/detail&gt;&lt;/soap:Fault&gt;&lt;/soap:Body&gt;&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string soap11GenericFault {
            get {
                return ResourceManager.GetString("soap11GenericFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;&lt;s:Header&gt;&lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;{0}&lt;/a:Action&gt;&lt;a:MessageID&gt;urn:uuid:{1}&lt;/a:MessageID&gt;&lt;a:ReplyTo&gt;&lt;a:Address&gt;http://www.w3.org/2005/08/addressing/anonymous&lt;/a:Address&gt;&lt;/a:ReplyTo&gt;&lt;a:To s:mustUnderstand=&quot;1&quot;&gt;{2}&lt;/a:To&gt;&lt;/s:Header&gt;&lt;s:Body&gt;{3}&lt;/s:Body&gt;&lt;/s:Envelope&gt;.
        /// </summary>
        internal static string soap12Envelope {
            get {
                return ResourceManager.GetString("soap12Envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;&lt;env:Body&gt;&lt;env:Fault&gt;&lt;env:Code&gt;&lt;env:Value&gt;{0}&lt;/env:Value&gt;&lt;env:Subcode&gt;&lt;env:Value&gt;{1}&lt;/env:Value&gt;&lt;/env:Subcode&gt;&lt;/env:Code&gt;&lt;env:Reason&gt;{2}&lt;/env:Reason&gt;&lt;env:Detail&gt;{3}&lt;/env:Detail&gt;&lt;/env:Fault&gt;&lt;/env:Body&gt;&lt;/env:Envelope&gt;.
        /// </summary>
        internal static string soap12GenericFault {
            get {
                return ResourceManager.GetString("soap12GenericFault", resourceCulture);
            }
        }
    }
}
