CREATE TABLE [dbo].[CopiedMessage](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MessageId] [uniqueidentifier] NOT NULL,
	[CopiedDate] [datetime] NULL CONSTRAINT [DF_CopiedMessage_InsertedDate]  DEFAULT (getdate()),
 CONSTRAINT [PK_CopiedMessage] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MessageID] ON [dbo].[CopiedMessage]
(
	[MessageId] ASC
)
INCLUDE ( 	[CopiedDate]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

