CREATE TABLE [dbo].[Part](
	[MessageId] [uniqueidentifier] NOT NULL,
	[PartId] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Part_PartId]  DEFAULT (newid()),
	[PartName] [nvarchar](256) NOT NULL,
	[PartIndex] [int] NOT NULL,
	[ContentType] [nvarchar](50) NOT NULL,
	[CharSet] [nvarchar](50) NOT NULL,
	[TextData] [nvarchar](max) NULL,
	[ImageData] [image] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Part] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[Part]  WITH CHECK ADD  CONSTRAINT [FK_Part_MessageId] FOREIGN KEY([MessageId])
REFERENCES [dbo].[Message] ([MessageId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Part] CHECK CONSTRAINT [FK_Part_MessageId]
GO

CREATE NONCLUSTERED INDEX [IX_Part_MessageId_PartId] ON [dbo].[Part]
(
	[MessageId] ASC
)
INCLUDE ( 	[PartId]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE UNIQUE NONCLUSTERED INDEX [U_PartID] ON [dbo].[Part]
(
	[PartId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

