
using System;

namespace Avista.ESB.Admin.Utility
{
    /// <summary>
    /// The event handler delegate for output events generated by the <see cref="ColorConsole"/>. The
    /// <see cref="ColorConsole"/> can be configured to notify event handlers whenever output is written
    /// to the console. To receive these notifications the interested parties must implement an
    /// <see cref="OutputEventHandler"/> and register it by calling <see cref="ColorConsole.AddOutputEventHandler"/>.
    /// </summary>
    /// <param name="sender">The object that triggered the event. This will always be null.</param>
    /// <param name="eventArgs">The event arguments.</param>
    public delegate void OutputEventHandler(object sender, OutputEventArgs eventArgs);
}
